name: 'IndexNow'
on:
  schedule:
    # Set the schedule time
    - cron: '0 2 * * *'
  workflow_dispatch: {}

jobs:
  check-and-submit:
    runs-on: ubuntu-latest
    steps:
      - name: indexnow-action
        uses: bojieyang/indexnow-action@v2
        with:
          sitemap-location: 'https://0xarch.github.io/sitemap.xml'
          key: ${{ secrets.INDEXNOWKEY }}